name: CI

on: [push, pull_request]

env:
  HADOOP_USER_NAME: hive

jobs:
  maven-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'maven'
      - name: Configure Problem Matchers
        run: |
          echo "::add-matcher::.github/problem-matcher.json"
          echo "::remove-matcher owner=java::"
      - name: Maven Checks
        run: |
          ./mvnw -B clean install
      - name: Annotate run
        uses: trinodb/github-actions/action-surefire-report@b63800bedfbc7ab1ff2e5fe7eaecf5ab82ce6a70
        if: always()
        with:
          fail_if_no_tests: false
          skip_publishing: true
